# Harmony Jekyll theme general configurations 

# Base URL
#baseurl: /harmony

# Site live URL
# url: http://dariusbakunas.github.io

# Localhost 
#url: http://192.168.0.102:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Darius Blog
  # Little description about your site
  description: Darius Blog
  meta_description: Darius Bakunas personal blog.
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Darius Bakunas
    email: bakunas@gmail.com
    url: http://dariusbakunas.github.io

  # Google Analytics key, leave blank to ignore
  # google_analytics_key: UA-55669408-1

  # Profile links, leave blank to ignore
  social: 
    github: dariusbakunas
    twitter: dariusbakunas
    facebook: dariusbakunas
    gplus: +DariusBakunas
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed